#!/bin/bash

work_dir=$PWD

set -ea
export $(cat star_burger/.env  | grep ROLLBAR | tr -d \")
set +a

git pull
GIT_HASH=$(git rev-parse --short HEAD)

if [ -e "venv/bin/activate" ]; then
    echo "activating venv"
    source venv/bin/activate
else
    echo "Creating venv..."
    python -m venv venv
    source venv/bin/activate
fi

echo "Installing requirements..."
pip install -r requirements.txt

echo "Installing node packages"
cd ./frontend
npm ci --dev
echo "Installing front packages"
./node_modules/.bin/parcel build ./bundles-src/index.js --dist-dir $work_dir/static/bundles

echo "Checking migration"
python3 $work_dir/backend/manage.py makemigrations --dry-run --check
echo "Migrating..."
python3 $work_dir/backend/manage.py migrate --noinput
echo "collect static..."
python3 $work_dir/backend/manage.py collectstatic --noinput
echo "Reload nginx"
systemctl reload nginx.service
echo "Reload Gunicorn"
systemctl restart star-burger.service

echo "Deployed"

curl -H "X-Rollbar-Access-Token: ${ROLLBAR_KEY}" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d "{\"environment\": \"production\", \"revision\": \"${GIT_HASH}\", \"rollbar_name\": \"Anton\", \"local_username\": \"$(whoami)\", \"comment\": \"deployment\", \"status\": \"succeeded\"}"
