version: '3.4'
services:
  frontend:
    image: star-burger_frontend:v1.0
    build:
      context: .
      target: frontend
  static:
    image: star-burger_static:v1.0
    build:
      context: .
      target: static
  gunicorn:
    image: star-burger_gunicorn:v1.0
    build:
      context: .
      target: gunicorn
    network_mode: "host"  


